A.L.E: Arcade Learning Environment (version 0.8.1+53f58b7)
[Powered by Stella]
/home/fs01/dje4001/.conda/envs/ataridqn/lib/python3.9/site-packages/gymnasium/utils/passive_env_checker.py:364: UserWarning: [33mWARN: No render fps was declared in the environment (env.metadata['render_fps'] is None or not defined), rendering may occur at inconsistent fps.[0m
  logger.warn(
cpu
Traceback (most recent call last):
  File "/home/fs01/dje4001/dqnthreat/dqnthreat/dqn_atari_stripped.py", line 207, in <module>
    set_diff.capture_video(obs,terminated,'/home/fs01/dje4001/dqnthreat/noise_video_nonoise/') #Generate recording of obs before agent sees
  File "/home/fs01/dje4001/dqnthreat/dqnthreat/ChangeDifficulty.py", line 38, in capture_video
    os.makedirs(drop_folder)
  File "/home/fs01/dje4001/.conda/envs/ataridqn/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/fs01/dje4001/dqnthreat/noise_video_nonoise/'
Exception ignored in: <function VectorEnv.__del__ at 0x14784a7483a0>
Traceback (most recent call last):
  File "/home/fs01/dje4001/.conda/envs/ataridqn/lib/python3.9/site-packages/gymnasium/vector/vector_env.py", line 329, in __del__
  File "/home/fs01/dje4001/.conda/envs/ataridqn/lib/python3.9/site-packages/gymnasium/vector/vector_env.py", line 271, in close
  File "/home/fs01/dje4001/.conda/envs/ataridqn/lib/python3.9/site-packages/gymnasium/vector/sync_vector_env.py", line 217, in close_extras
  File "/home/fs01/dje4001/.conda/envs/ataridqn/lib/python3.9/site-packages/gymnasium/vector/sync_vector_env.py", line 217, in <listcomp>
  File "/home/fs01/dje4001/.conda/envs/ataridqn/lib/python3.9/site-packages/gymnasium/core.py", line 422, in close
  File "/home/fs01/dje4001/.conda/envs/ataridqn/lib/python3.9/site-packages/gymnasium/core.py", line 422, in close
  File "/home/fs01/dje4001/.conda/envs/ataridqn/lib/python3.9/site-packages/gymnasium/core.py", line 422, in close
  [Previous line repeated 6 more times]
  File "/home/fs01/dje4001/.conda/envs/ataridqn/lib/python3.9/site-packages/gymnasium/wrappers/record_video.py", line 217, in close
  File "/home/fs01/dje4001/.conda/envs/ataridqn/lib/python3.9/site-packages/gymnasium/wrappers/record_video.py", line 193, in close_video_recorder
  File "/home/fs01/dje4001/.conda/envs/ataridqn/lib/python3.9/site-packages/gymnasium/wrappers/monitoring/video_recorder.py", line 155, in close
AttributeError: 'NoneType' object has no attribute 'DependencyNotInstalled'
Exception ignored in: <function VideoRecorder.__del__ at 0x14784ae36ee0>
Traceback (most recent call last):
  File "/home/fs01/dje4001/.conda/envs/ataridqn/lib/python3.9/site-packages/gymnasium/wrappers/monitoring/video_recorder.py", line 182, in __del__
AttributeError: 'NoneType' object has no attribute 'warn'
